name: Merge Dev to Staging
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

# 버전 minor와 major 중 어떤것을 올릴것인지  선택 가능
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'minor'
          - 'major'

jobs:
  # staging 브랜치가 존재한다면 삭제
  delete-staging-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Delete an exiting staging branch
        run: |
          if [ -n "$(git ls-remote --heads origin staging)" ]; then
            git fetch --prune
            git push origin --delete staging
          fi
            echo "staging branch doesn't exist"
  

  # dev 브랜치로 checkout 및 버전 변경 후 commit
  # dev 브랜치에서 staging 브랜치 생성 및 staging 브랜치 push
  dev-versioning:
    if: ${{ success() }}
    needs: delete-staging-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Get package version
        id: package-version-old
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: version minor
        if: ${{ inputs.version == 'minor'}}
        run: |
          npm version preminor --no-git-tag-version --no-workspaces-update --preid=rc

      - name: version major
        if: ${{ inputs.version == 'major'}}
        run: |
          npm version premajor --no-git-tag-version --no-workspaces-update --preid=rc

      - name: Get package version
        id: package-version-new
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: checkout staging and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Version v${{ steps.package-version-old.outputs.current-version }} to v${{ steps.package-version-new.outputs.current-version }}"
          git checkout -b staging
          git push --set-upstream origin staging

  deploy-prod-server:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

