name: Merge Dev to Staging

# 버전 minor와 major 중 어떤것을 올릴것인지  선택 가능
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  checkout-dev-versioning:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Pull Request
        run: gh pr create --title "Merge main to dev" --body "main to dev" --assignee @me --base dev
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge --merge ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}




