name: Merge Staging to Dev

# 버전 minor와 major 중 어떤것을 올릴것인지  선택 가능
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  checkout-dev-versioning:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: create merge-staging-to-dev branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b merge-staging-to-dev
          git add .
          git push --set-upstream origin merge-staging-to-dev


      - name: Create Pull Request
        run: gh pr create --title "Merge Staging to dev" --body "staging to dev" --assignee @me --base dev
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge --merge ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  delete-staiging-branch:
    if: ${{ success() }}
    needs: checkout-dev-versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Delete an exiting staging branch
        run: |
          if [ -n "$(git ls-remote --heads origin staging)" ]; then
            git fetch --prune
            git push origin --delete staging
          if [ -n "$(git ls-remote --heads origin merge-staging-to-dev)" ]; then
            git fetch --prune
            git push origin --delete merge-staging-to-dev
          fi
            echo "staging branch doesn't exist"



