name: Merge Staging to Dev

# 버전 minor와 major 중 어떤것을 올릴것인지  선택 가능
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-merge-staging-to-dev:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: merge-staging-to-dev
      - name: Create Pull Request
        run: |
          PR_OUTPUT=$(gh pr create --title "Merge Staging to Dev" --body "staging to dev" --assignee @me --base dev)
          echo "PR_OUTPUT=$PR_OUTPUT" >> $GITHUB_ENV
          PR_NUMBER=$(echo "$PR_OUTPUT" | grep -oP '(?<=/pull/)\d+')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge $PR_NUMBER --merge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  delete-staiging-branch:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Delete an exiting staging branch
        run: |
          if [ -n "$(git ls-remote --heads origin staging)" ]; then
            git fetch --prune
            git push origin --delete staging
          if [ -n "$(git ls-remote --heads origin merge-staging-to-dev)" ]; then
            git fetch --prune
            git push origin --delete merge-staging-to-dev
          fi
            echo "staging branch doesn't exist"



